package modellfreigabe

import "github.com/cucumber/godog"

func (s *suite) initialize(sc *godog.ScenarioContext) {
	sc.After(s.afterScenario)
	s.registerSetup(sc)
	s.registerAppActions(sc)
	s.registerAppAssertions(sc)
	s.registerBrowser(sc)
}

func (s *suite) registerSetup(sc *godog.ScenarioContext) {
	sc.Step(`^eine zentrale OpenRouter-Verbindung mit synthetischem Testschlüssel eingerichtet ist$`, s.settingsReady)
	sc.Step(`^die Organisationen "([^"]+)" und "([^"]+)" über die öffentliche Organisationsgrenze angelegt sind$`, s.organizations)
	sc.Step(`^die Eino-Agenten "([^"]+)" und "([^"]+)" in "([^"]+)" sowie "([^"]+)" in "([^"]+)" über die öffentliche Agentengrenze angelegt sind$`, s.agents)
	sc.Step(`^ein kontrollierter OpenRouter-Modellzugang bereitsteht$`, s.providerReady)
	sc.Step(`^die Organisationen "([^"]+)" und "([^"]+)" sowie die Eino-Agenten "([^"]+)" und "([^"]+)" in "([^"]+)" bestehen$`, s.browserEntities)
	sc.Step(`^die Verbindung ist für "([^"]+)" auf "([^"]+)" freigegeben$`, s.grantedLevel)
	sc.Step(`^die Verbindung ist für "([^"]+)" und "([^"]+)" ausdrücklich freigegeben$`, s.grantedOrganizationAgent)
	sc.Step(`^die Verbindung ist für "([^"]+)", "([^"]+)" und "([^"]+)" ausdrücklich freigegeben$`, s.grantedOrganizationAgents)
	sc.Step(`^"([^"]+)" und "([^"]+)" sind ausdrücklich freigegeben$`, s.grantedOrganizationAgent)
	sc.Step(`^"([^"]+)", "([^"]+)" und "([^"]+)" sind ausdrücklich freigegeben$`, s.grantedOrganizationAgents)
}

func (s *suite) registerAppActions(sc *godog.ScenarioContext) {
	sc.Step(`^ich als Betreiber die zentrale Verbindung für "([^"]+)" freigebe$`, s.grantOrganization)
	sc.Step(`^ich als Betreiber die Verbindung zusätzlich für "([^"]+)" freigebe$`, s.grantAgent)
	sc.Step(`^ich die zentrale Verbindung dem Eino-Agenten "([^"]+)" zuordnen möchte$`, s.authorizeAgent)
	sc.Step(`^ich die Verbindungsreferenz für "([^"]+)" aus "([^"]+)" oder "([^"]+)" aus "([^"]+)" bei der öffentlichen Modellzugangsgrenze verwende$`, s.crossAgentAttempts)
	sc.Step(`^ich als Betreiber die Freigabe für "([^"]+)" widerrufe$`, s.revoke)
	sc.Step(`^ein Modellzugangsversuch für "([^"]+)" wartet vor dem tatsächlichen Anbieteraufruf$`, s.authorizeThenWait)
	sc.Step(`^der wartende Modellzugangsversuch fortgesetzt wird$`, s.resumeInvocation)
	sc.Step(`^ich eine weitere Organisation und darin einen Eino-Agenten über die öffentlichen Grenzen anlege$`, s.createAdditionalOrganization)
	sc.Step(`^ich einen weiteren Eino-Agenten in "([^"]+)" über die öffentliche Agentengrenze anlege$`, s.createAdditionalAgent)
	sc.Step(`^ein Modellzugangsversuch mit "([^"]+)" als delegierendem und "([^"]+)" als ausführendem Eino-Agenten ankommt$`, s.delegatedAttempt)
	sc.Step(`^ich als Betreiber den zentralen Testschlüssel über Settings ersetze$`, s.rotateKey)
	sc.Step(`^ich die öffentlichen Freigabeansichten und JSON-Antworten für Organisation und Agent abrufe$`, s.fetchViews)
	sc.Step(`^ich als Betreiber die zentrale Verbindung über Settings trenne$`, s.disconnectSettings)
	sc.Step(`^ich sie mit einem neuen synthetischen Testschlüssel erneut verbinde$`, s.reconnectSettings)
	sc.Step(`^ich sie unter derselben Verbindungsreferenz mit einem neuen synthetischen Testschlüssel erneut verbinde$`, s.reconnectSameReference)
	sc.Step(`^der aufrufende Teil die zurückgehaltene Bindung am serverseitigen Verbindungsresolver einlöst$`, s.releaseAuthorizedBinding)
	sc.Step(`^der aufrufende Teil hält diesen autorisierten Aufruf vor der finalen serverseitigen Schlüsselauflösung und Providergrenze zurück$`, s.holdAuthorizedBinding)
	sc.Step(`^der aufrufende Teil den zurückgehaltenen Aufruf fortsetzt$`, s.releaseAuthorizedBinding)
	sc.Step(`^ich als Betreiber zuerst "([^"]+)" und danach "([^"]+)" für die erneuerte Verbindung ausdrücklich freigebe$`, s.regrantAfterReconnect)
}

func (s *suite) registerAppAssertions(sc *godog.ScenarioContext) {
	sc.Step(`^zeigt die öffentliche Freigabeansicht "([^"]+)" als freigegeben und "([^"]+)" als nicht freigegeben$`, s.organizationGrantedAgentNot)
	sc.Step(`^ein Modellzugangsversuch für "([^"]+)" wird vor Kontakt zum kontrollierten Modellzugang wegen fehlender Agentenfreigabe abgewiesen$`, s.agentDenied)
	sc.Step(`^ist die Verbindung für "([^"]+)" zulässig$`, s.agentAllowed)
	sc.Step(`^ein Modellzugangsversuch für "([^"]+)" erreicht den kontrollierten OpenRouter-Modellzugang genau einmal$`, s.agentCalledOnce)
	sc.Step(`^Modellzugangsversuche für "([^"]+)" und "([^"]+)" erreichen ihn nicht$`, s.twoAgentsDenied)
	sc.Step(`^Modellzugangsversuche für "([^"]+)" und "([^"]+)" erreichen den kontrollierten Modellzugang nicht$`, s.twoAgentsDenied)
	sc.Step(`^wird die Zuordnung mit dem Grund "([^"]+)" abgelehnt$`, s.decisionDeniedForReason)
	sc.Step(`^ein Modellzugangsversuch für "([^"]+)" erreicht den kontrollierten Modellzugang nicht$`, s.agentNotCalled)
	sc.Step(`^werden beide Versuche vor Kontakt zum kontrollierten Modellzugang abgewiesen$`, s.bothDenied)
	sc.Step(`^die Antwort enthält keine Schlüssel- oder fremden Organisationsdaten$`, s.noForeignData)
	sc.Step(`^zeigt die öffentliche Freigabeansicht "([^"]+)" als nicht freigegeben$`, s.agentStatusNotGranted)
	sc.Step(`^ein neuer Modellzugangsversuch für "([^"]+)" wird vor Kontakt zum kontrollierten Modellzugang abgewiesen$`, s.agentNotCalled)
	sc.Step(`^ein Modellzugangsversuch für "([^"]+)" erreicht ihn weiterhin$`, s.agentCalled)
	sc.Step(`^werden neue Modellzugangsversuche für "([^"]+)" und "([^"]+)" vor Kontakt zum kontrollierten Modellzugang abgewiesen$`, s.twoAgentsDenied)
	sc.Step(`^die öffentliche Freigabeansicht nennt die fehlende Organisationsfreigabe$`, s.organizationReason)
	sc.Step(`^wird der Aufruf mit dem Grund "([^"]+)" abgewiesen$`, s.invocationDeniedForReason)
	sc.Step(`^wird die Schlüsselauflösung mit dem Grund "([^"]+)" verweigert$`, s.invocationDeniedForReason)
	sc.Step(`^der kontrollierte Modellzugang hat keine synthetische Provider-POST-Anfrage aus diesem Aufruf erhalten$`, s.noCallFromBinding)
	sc.Step(`^der kontrollierte Modellzugang hat keinen Aufruf erhalten$`, s.noCalls)
	sc.Step(`^haben die neue Organisation und beide neuen Agenten keine OpenRouter-Freigabe$`, s.newEntitiesNotGranted)
	sc.Step(`^ihre Modellzugangsversuche erreichen den kontrollierten Modellzugang nicht$`, s.newEntitiesDenied)
	sc.Step(`^wird der Versuch wegen fehlender Freigabe für "([^"]+)" vor Kontakt zum kontrollierten Modellzugang abgewiesen$`, s.delegatedDenied)
	sc.Step(`^die Freigabe für "([^"]+)" wird nicht auf "([^"]+)" übertragen$`, s.noInheritedGrant)
	sc.Step(`^bleiben nur "([^"]+)" und "([^"]+)" freigegeben$`, s.onlyOriginalGrants)
	sc.Step(`^zeigen sie die Verbindungsreferenz und den jeweiligen Freigabestatus$`, s.publicViewFields)
	sc.Step(`^sie enthalten weder den synthetischen Testschlüssel noch einen entschlüsselten Teil davon$`, s.noSecretsInViews)
	sc.Step(`^der Testschlüssel erscheint nicht in Agentenkonfiguration oder Modellzugangsfehlern$`, s.noSecretsInAgentOrError)
	sc.Step(`^ein Modellzugangsversuch für "([^"]+)" erreicht den kontrollierten Modellzugang$`, s.agentCalled)
	sc.Step(`^zeigt Settings dieselbe zentrale Verbindungsreferenz ohne Schlüssel$`, s.reconnectedReference)
	sc.Step(`^die früheren Freigaben für "([^"]+)" und "([^"]+)" sind nicht mehr wirksam$`, s.oldGrantsInvalid)
	sc.Step(`^erreicht ein neuer Modellzugangsversuch für "([^"]+)" den kontrollierten Modellzugang genau einmal$`, s.reconnectedCallOnce)
	sc.Step(`^öffentliche Settings-, Freigabe- und Modellzugangsantworten enthalten keinen der Testschlüssel$`, s.reconnectNoSecrets)
	sc.Step(`^die öffentliche Aufrufgrenze hat einen Modellzugangsversuch für "([^"]+)" positiv autorisiert$`, s.positivelyAuthorized)
	sc.Step(`^der aufrufende Teil hält diese autorisierte Bindung vor dem tatsächlichen Anbieteraufruf zurück$`, s.holdAuthorizedBinding)
	sc.Step(`^weist der Resolver die alte Bindung als widerrufen ab$`, s.oldBindingRevoked)
	sc.Step(`^der kontrollierte Modellzugang hat keinen Aufruf aus dieser Bindung erhalten$`, s.noCallFromBinding)
	sc.Step(`^die früheren Freigaben für "([^"]+)" und "([^"]+)" sind nicht wieder wirksam$`, s.oldGrantsInvalid)
}

func (s *suite) registerBrowser(sc *godog.ScenarioContext) {
	sc.Step(`^ich "Settings > Modellanbieter > OpenRouter" im echten Browser öffne$`, s.openSettingsBrowser)
	sc.Step(`^sehe ich die zentrale Verbindungsreferenz ohne Schlüssel$`, s.browserReference)
	sc.Step(`^"([^"]+)" und "([^"]+)" werden als nicht freigegeben angezeigt$`, s.browserOrganizationsNotGranted)
	sc.Step(`^ich "([^"]+)" ausdrücklich freigebe$`, s.browserGrant)
	sc.Step(`^sehe ich "([^"]+)" als freigegeben und "([^"]+)" und "([^"]+)" weiterhin als nicht freigegeben$`, s.browserOrganizationGranted)
	sc.Step(`^sehe ich "([^"]+)" als freigegeben und "([^"]+)" weiterhin als nicht freigegeben$`, s.browserAgentGranted)
	sc.Step(`^ich in den OpenRouter-Einstellungen die Freigabe für "([^"]+)" widerrufe$`, s.browserRevoke)
	sc.Step(`^sehe ich "([^"]+)" als nicht freigegeben und "([^"]+)" weiterhin als freigegeben$`, s.browserAgentRevoked)
	sc.Step(`^ich die Freigabe für "([^"]+)" widerrufe$`, s.browserRevoke)
	sc.Step(`^zeigt die Oberfläche die fehlende Organisationsfreigabe für beide Agenten$`, s.browserOrganizationReason)
	sc.Step(`^eine frühere Agentenfreigabe erscheint nicht als nutzbare Verbindung$`, s.browserNoUsableConnection)
	sc.Step(`^ich die OpenRouter-Einstellungen und die Agentenansicht für "([^"]+)" im echten Browser öffne$`, s.browserOpenSettingsAndAgent)
	sc.Step(`^enthalten sichtbare Seite und Browserantworten nur Verbindungsreferenz und Freigabestatus$`, s.browserPublicFields)
	sc.Step(`^weder der synthetische Testschlüssel noch ein Teil davon erscheint in HTML, JSON oder Formularfeldern$`, s.browserNoSecrets)
}
